baseURL = "https://shino16.github.io/blog/"
languageCode = "ja-jp"
title = "しのの備忘録"
theme = "pickles"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; shino16 <br /> コード片はCC0で配布します。ご自由にお使いください。"

# Google Analytics API key.
googleAnalytics = "UA-179412738-1"

summaryLength = 15

[markup.goldmark.renderer]
unsafe = true

[params]
  paginate = 10
  custom_css = ["/blog/css/custom.css"]
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "shino_skycrew"
  # Disqus shortname
  disqus = ""
#   author = "しの"
#   authorwebsite = "example.com"
#   avatar = "icon.jpg"
#   contact = "Your contact link (ex. mailto:foo@example.com)"
#   bio = "Your short bio"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "数学・競プロ"
  # Logo image. This is displayed ogp image.
  # logo = "penguin.jpg"
  thumbnail = "penguin.jpg"
  favicon = "icon.jpg"

[[menu.main]]
    name = "Archive"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

# [[menu.main]]
#     identifier = "theme"
#     name = "/theme"
#     weight = 3

# [[menu.main]]
#     parent = "theme"
#     name = "creating-a-new-theme"
#     url = "/posts/creating-a-new-theme"
#     weight = 1

# [[menu.main]]
#     parent = "theme"
#     name = "migrate-from-jekyll"
#     url = "/posts/migrate-from-jekyll"
#     weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"