name: publish
on: ["push"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive
      - name: Install Hugo
        run: sudo snap install hugo --channel=extended
      - name: Build pages
        run: hugo
      - name: Publish
        run: |
          git config --global user.name "shino16-sub"
          git config --global user.email "masato.sinokawa@gmail.com"
          cd public
          cat ./index.html
          git init
          git add .
          git commit -m "Automated commit"
          git remote add origin https://shino16:${{ secrets.GH_PAT }}@github.com/shino16/blog.git
          git push origin HEAD:master --force