name: publish
on: ["push"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # - name: Install Brew
      #   run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      # - name: Install Hugo
      #   run: brew install hugo
      # - name: Build pages
      #   run: hugo
      - name: Do smth
        run: mkdir public && echo "Hello!" > public/out.txt
      - name: Publish
        run: |
          git config --global user.name "masatosinokawa@gmail.com"
          git config --global user.email "shino16"
          cd public
          git init
          git add .
          git commit -m "Automated commit"
          git remote add origin "https://shino16:$GH_PAT@github.com/shino16/blog.git"
          git push origin HEAD:master --force